trigger:
- main

pr:
- main

pool:
  name: Default

steps:

- checkout: self

- script: |
    terraform version
  displayName: "Terraform Version"

- script: |
    cd environments/dev
    terraform fmt -check -recursive ../..
  displayName: "Terraform Format Check"

- script: |
    cd environments/dev

    terraform init \
      -backend=false

    terraform validate
  displayName: "Terraform Validate"