trigger:
- main

pr:
- main

pool:
  name: Default

steps:

- checkout: self

- script: |
    terraform version
  displayName: "Terraform Version"

- script: |
    cd environments/dev
    terraform fmt -check -recursive ../..
  displayName: "Terraform Format Check"

- script: |
    cd environments/dev

    terraform init \
      -backend=false

    terraform validate
  displayName: "Terraform Validate"

- script: |
    mkdir output
    echo "Terraform Validation Passed" > output/result.txt
  displayName: "Generate Artifact"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'output'
    ArtifactName: 'validation-output'
  displayName: "Publish Artifact"